name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Deploy when code is pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # Use Node.js version 16 or later
        cache: 'npm'     # Cache dependencies for faster builds

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build and export the Next.js app
    - name: Build the app
      run: npm run build && npm run export

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out # Static files output folder
